# Generated by carnix 0.9.8: carnix generate-nix --src .
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
rec {
  crates = cratesIO // rec {
# fitnesstrax-0.1.0

    crates.fitnesstrax."0.1.0" = deps: { features?(features_.fitnesstrax."0.1.0" deps {}) }: buildRustCrate {
      crateName = "fitnesstrax";
      version = "0.1.0";
      authors = [ "Savanni D'Gerinel <savanni@luminescent-dreams.com>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      dependencies = mapFeatures features ([
        (cratesIO.crates."chrono"."${deps."fitnesstrax"."0.1.0"."chrono"}" deps)
        (cratesIO.crates."chrono_tz"."${deps."fitnesstrax"."0.1.0"."chrono_tz"}" deps)
        (cratesIO.crates."dimensioned"."${deps."fitnesstrax"."0.1.0"."dimensioned"}" deps)
        (cratesIO.crates."emseries"."${deps."fitnesstrax"."0.1.0"."emseries"}" deps)
        (cratesIO.crates."serde"."${deps."fitnesstrax"."0.1.0"."serde"}" deps)
        (cratesIO.crates."serde_derive"."${deps."fitnesstrax"."0.1.0"."serde_derive"}" deps)
        (cratesIO.crates."serde_json"."${deps."fitnesstrax"."0.1.0"."serde_json"}" deps)
      ]);
    };
    features_.fitnesstrax."0.1.0" = deps: f: updateFeatures f (rec {
      chrono = fold recursiveUpdate {} [
        { "${deps.fitnesstrax."0.1.0".chrono}"."serde" = true; }
        { "${deps.fitnesstrax."0.1.0".chrono}".default = true; }
      ];
      chrono_tz = fold recursiveUpdate {} [
        { "${deps.fitnesstrax."0.1.0".chrono_tz}"."serde" = true; }
        { "${deps.fitnesstrax."0.1.0".chrono_tz}".default = true; }
      ];
      dimensioned."${deps.fitnesstrax."0.1.0".dimensioned}".default = true;
      emseries."${deps.fitnesstrax."0.1.0".emseries}".default = true;
      fitnesstrax."0.1.0".default = (f.fitnesstrax."0.1.0".default or true);
      serde."${deps.fitnesstrax."0.1.0".serde}".default = true;
      serde_derive."${deps.fitnesstrax."0.1.0".serde_derive}".default = true;
      serde_json."${deps.fitnesstrax."0.1.0".serde_json}".default = true;
    }) [
      (cratesIO.features_.chrono."${deps."fitnesstrax"."0.1.0"."chrono"}" deps)
      (cratesIO.features_.chrono_tz."${deps."fitnesstrax"."0.1.0"."chrono_tz"}" deps)
      (cratesIO.features_.dimensioned."${deps."fitnesstrax"."0.1.0"."dimensioned"}" deps)
      (cratesIO.features_.emseries."${deps."fitnesstrax"."0.1.0"."emseries"}" deps)
      (cratesIO.features_.serde."${deps."fitnesstrax"."0.1.0"."serde"}" deps)
      (cratesIO.features_.serde_derive."${deps."fitnesstrax"."0.1.0"."serde_derive"}" deps)
      (cratesIO.features_.serde_json."${deps."fitnesstrax"."0.1.0"."serde_json"}" deps)
    ];


# end

  };

  fitnesstrax = crates.crates.fitnesstrax."0.1.0" deps;
  __all = [ (fitnesstrax {}) ];
  deps.aho_corasick."0.6.10" = {
    memchr = "2.2.1";
  };
  deps.autocfg."0.1.6" = {};
  deps.cfg_if."0.1.9" = {};
  deps.chrono."0.4.9" = {
    libc = "0.2.62";
    num_integer = "0.1.41";
    num_traits = "0.2.8";
    serde = "1.0.100";
    time = "0.1.42";
  };
  deps.chrono_tz."0.4.1" = {
    chrono = "0.4.9";
    serde = "1.0.100";
    parse_zoneinfo = "0.1.1";
  };
  deps.dimensioned."0.7.0" = {
    generic_array = "0.11.1";
    num_traits = "0.2.8";
    serde = "1.0.100";
    typenum = "1.11.2";
  };
  deps.emseries."0.4.0" = {
    chrono = "0.4.9";
    chrono_tz = "0.4.1";
    dimensioned = "0.7.0";
    serde = "1.0.100";
    serde_derive = "1.0.100";
    serde_json = "1.0.40";
    uuid = "0.6.5";
    yaml_rust = "0.4.3";
  };
  deps.fitnesstrax."0.1.0" = {
    chrono = "0.4.9";
    chrono_tz = "0.4.1";
    dimensioned = "0.7.0";
    emseries = "0.4.0";
    serde = "1.0.100";
    serde_derive = "1.0.100";
    serde_json = "1.0.40";
  };
  deps.fuchsia_cprng."0.1.1" = {};
  deps.generic_array."0.11.1" = {
    typenum = "1.11.2";
  };
  deps.itoa."0.4.4" = {};
  deps.lazy_static."1.4.0" = {};
  deps.libc."0.2.62" = {};
  deps.linked_hash_map."0.5.2" = {};
  deps.memchr."2.2.1" = {};
  deps.num_integer."0.1.41" = {
    num_traits = "0.2.8";
    autocfg = "0.1.6";
  };
  deps.num_traits."0.2.8" = {
    autocfg = "0.1.6";
  };
  deps.parse_zoneinfo."0.1.1" = {
    regex = "0.2.11";
  };
  deps.proc_macro2."1.0.3" = {
    unicode_xid = "0.2.0";
  };
  deps.quote."1.0.2" = {
    proc_macro2 = "1.0.3";
  };
  deps.rand."0.4.6" = {
    rand_core = "0.3.1";
    rdrand = "0.4.0";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.62";
    winapi = "0.3.8";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.2";
  };
  deps.rand_core."0.4.2" = {};
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.redox_syscall."0.1.56" = {};
  deps.regex."0.2.11" = {
    aho_corasick = "0.6.10";
    memchr = "2.2.1";
    regex_syntax = "0.5.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.4";
  };
  deps.regex_syntax."0.5.6" = {
    ucd_util = "0.1.5";
  };
  deps.ryu."1.0.0" = {};
  deps.serde."1.0.100" = {};
  deps.serde_derive."1.0.100" = {
    proc_macro2 = "1.0.3";
    quote = "1.0.2";
    syn = "1.0.5";
  };
  deps.serde_json."1.0.40" = {
    itoa = "0.4.4";
    ryu = "1.0.0";
    serde = "1.0.100";
  };
  deps.syn."1.0.5" = {
    proc_macro2 = "1.0.3";
    quote = "1.0.2";
    unicode_xid = "0.2.0";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.4.0";
  };
  deps.time."0.1.42" = {
    libc = "0.2.62";
    redox_syscall = "0.1.56";
    winapi = "0.3.8";
  };
  deps.typenum."1.11.2" = {};
  deps.ucd_util."0.1.5" = {};
  deps.unicode_xid."0.2.0" = {};
  deps.utf8_ranges."1.0.4" = {};
  deps.uuid."0.6.5" = {
    cfg_if = "0.1.9";
    rand = "0.4.6";
    serde = "1.0.100";
  };
  deps.winapi."0.3.8" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.yaml_rust."0.4.3" = {
    linked_hash_map = "0.5.2";
  };
}
