# Generated by carnix 0.10.0: carnix generate-nix --src .
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
rec {
  crates = cratesIO // rec {
# fitnesstrax-0.1.0

    crates.fitnesstrax."0.1.0" = deps: { features?(features_.fitnesstrax."0.1.0" deps {}) }: buildRustCrate {
      crateName = "fitnesstrax";
      version = "0.1.0";
      authors = [ "Savanni D'Gerinel <savanni@luminescent-dreams.com>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] /home/savanni/src/luminescent-dreams/fitnesstrax/gtk/../fitnesstrax-lib;
      dependencies = mapFeatures features ([
        (cratesIO.crates."chrono"."${deps."fitnesstrax"."0.1.0"."chrono"}" deps)
        (cratesIO.crates."chrono_tz"."${deps."fitnesstrax"."0.1.0"."chrono_tz"}" deps)
        (cratesIO.crates."dimensioned"."${deps."fitnesstrax"."0.1.0"."dimensioned"}" deps)
        (cratesIO.crates."emseries"."${deps."fitnesstrax"."0.1.0"."emseries"}" deps)
        (cratesIO.crates."serde"."${deps."fitnesstrax"."0.1.0"."serde"}" deps)
        (cratesIO.crates."serde_derive"."${deps."fitnesstrax"."0.1.0"."serde_derive"}" deps)
        (cratesIO.crates."serde_json"."${deps."fitnesstrax"."0.1.0"."serde_json"}" deps)
      ]);
    };
    features_.fitnesstrax."0.1.0" = deps: f: updateFeatures f (rec {
      chrono = fold recursiveUpdate {} [
        { "${deps.fitnesstrax."0.1.0".chrono}"."serde" = true; }
        { "${deps.fitnesstrax."0.1.0".chrono}".default = true; }
      ];
      chrono_tz = fold recursiveUpdate {} [
        { "${deps.fitnesstrax."0.1.0".chrono_tz}"."serde" = true; }
        { "${deps.fitnesstrax."0.1.0".chrono_tz}".default = true; }
      ];
      dimensioned."${deps.fitnesstrax."0.1.0".dimensioned}".default = true;
      emseries."${deps.fitnesstrax."0.1.0".emseries}".default = true;
      fitnesstrax."0.1.0".default = (f.fitnesstrax."0.1.0".default or true);
      serde."${deps.fitnesstrax."0.1.0".serde}".default = true;
      serde_derive."${deps.fitnesstrax."0.1.0".serde_derive}".default = true;
      serde_json."${deps.fitnesstrax."0.1.0".serde_json}".default = true;
    }) [
      (cratesIO.features_.chrono."${deps."fitnesstrax"."0.1.0"."chrono"}" deps)
      (cratesIO.features_.chrono_tz."${deps."fitnesstrax"."0.1.0"."chrono_tz"}" deps)
      (cratesIO.features_.dimensioned."${deps."fitnesstrax"."0.1.0"."dimensioned"}" deps)
      (cratesIO.features_.emseries."${deps."fitnesstrax"."0.1.0"."emseries"}" deps)
      (cratesIO.features_.serde."${deps."fitnesstrax"."0.1.0"."serde"}" deps)
      (cratesIO.features_.serde_derive."${deps."fitnesstrax"."0.1.0"."serde_derive"}" deps)
      (cratesIO.features_.serde_json."${deps."fitnesstrax"."0.1.0"."serde_json"}" deps)
    ];


# end
# fitnesstrax-gtk-0.1.0

    crates.fitnesstrax_gtk."0.1.0" = deps: { features?(features_.fitnesstrax_gtk."0.1.0" deps {}) }: buildRustCrate {
      crateName = "fitnesstrax-gtk";
      version = "0.1.0";
      authors = [ "savanni" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      crateBin =
        [{  name = "fitnesstrax-gtk";  path = "src/main.rs"; }];
      dependencies = mapFeatures features ([
        (cratesIO.crates."chrono"."${deps."fitnesstrax_gtk"."0.1.0"."chrono"}" deps)
        (cratesIO.crates."chrono_tz"."${deps."fitnesstrax_gtk"."0.1.0"."chrono_tz"}" deps)
        (cratesIO.crates."dimensioned"."${deps."fitnesstrax_gtk"."0.1.0"."dimensioned"}" deps)
        (cratesIO.crates."emseries"."${deps."fitnesstrax_gtk"."0.1.0"."emseries"}" deps)
        (crates."fitnesstrax"."${deps."fitnesstrax_gtk"."0.1.0"."fitnesstrax"}" deps)
        (cratesIO.crates."gio"."${deps."fitnesstrax_gtk"."0.1.0"."gio"}" deps)
        (cratesIO.crates."glib"."${deps."fitnesstrax_gtk"."0.1.0"."glib"}" deps)
        (cratesIO.crates."gtk"."${deps."fitnesstrax_gtk"."0.1.0"."gtk"}" deps)
        (cratesIO.crates."regex"."${deps."fitnesstrax_gtk"."0.1.0"."regex"}" deps)
        (cratesIO.crates."serde"."${deps."fitnesstrax_gtk"."0.1.0"."serde"}" deps)
        (cratesIO.crates."serde_yaml"."${deps."fitnesstrax_gtk"."0.1.0"."serde_yaml"}" deps)
        (cratesIO.crates."tzdata"."${deps."fitnesstrax_gtk"."0.1.0"."tzdata"}" deps)
      ]);
    };
    features_.fitnesstrax_gtk."0.1.0" = deps: f: updateFeatures f (rec {
      chrono = fold recursiveUpdate {} [
        { "${deps.fitnesstrax_gtk."0.1.0".chrono}"."serde" = true; }
        { "${deps.fitnesstrax_gtk."0.1.0".chrono}".default = true; }
      ];
      chrono_tz = fold recursiveUpdate {} [
        { "${deps.fitnesstrax_gtk."0.1.0".chrono_tz}"."serde" = true; }
        { "${deps.fitnesstrax_gtk."0.1.0".chrono_tz}".default = true; }
      ];
      dimensioned."${deps.fitnesstrax_gtk."0.1.0".dimensioned}".default = true;
      emseries."${deps.fitnesstrax_gtk."0.1.0".emseries}".default = true;
      fitnesstrax."${deps.fitnesstrax_gtk."0.1.0".fitnesstrax}".default = true;
      fitnesstrax_gtk."0.1.0".default = (f.fitnesstrax_gtk."0.1.0".default or true);
      gio = fold recursiveUpdate {} [
        { "${deps.fitnesstrax_gtk."0.1.0".gio}"."v2_44" = true; }
        { "${deps.fitnesstrax_gtk."0.1.0".gio}".default = true; }
      ];
      glib."${deps.fitnesstrax_gtk."0.1.0".glib}".default = true;
      gtk = fold recursiveUpdate {} [
        { "${deps.fitnesstrax_gtk."0.1.0".gtk}"."v3_16" = true; }
        { "${deps.fitnesstrax_gtk."0.1.0".gtk}".default = true; }
      ];
      regex."${deps.fitnesstrax_gtk."0.1.0".regex}".default = true;
      serde = fold recursiveUpdate {} [
        { "${deps.fitnesstrax_gtk."0.1.0".serde}"."derive" = true; }
        { "${deps.fitnesstrax_gtk."0.1.0".serde}".default = true; }
      ];
      serde_yaml."${deps.fitnesstrax_gtk."0.1.0".serde_yaml}".default = true;
      tzdata."${deps.fitnesstrax_gtk."0.1.0".tzdata}".default = true;
    }) [
      (cratesIO.features_.chrono."${deps."fitnesstrax_gtk"."0.1.0"."chrono"}" deps)
      (cratesIO.features_.chrono_tz."${deps."fitnesstrax_gtk"."0.1.0"."chrono_tz"}" deps)
      (cratesIO.features_.dimensioned."${deps."fitnesstrax_gtk"."0.1.0"."dimensioned"}" deps)
      (cratesIO.features_.emseries."${deps."fitnesstrax_gtk"."0.1.0"."emseries"}" deps)
      (features_.fitnesstrax."${deps."fitnesstrax_gtk"."0.1.0"."fitnesstrax"}" deps)
      (cratesIO.features_.gio."${deps."fitnesstrax_gtk"."0.1.0"."gio"}" deps)
      (cratesIO.features_.glib."${deps."fitnesstrax_gtk"."0.1.0"."glib"}" deps)
      (cratesIO.features_.gtk."${deps."fitnesstrax_gtk"."0.1.0"."gtk"}" deps)
      (cratesIO.features_.regex."${deps."fitnesstrax_gtk"."0.1.0"."regex"}" deps)
      (cratesIO.features_.serde."${deps."fitnesstrax_gtk"."0.1.0"."serde"}" deps)
      (cratesIO.features_.serde_yaml."${deps."fitnesstrax_gtk"."0.1.0"."serde_yaml"}" deps)
      (cratesIO.features_.tzdata."${deps."fitnesstrax_gtk"."0.1.0"."tzdata"}" deps)
    ];


# end

  };

  fitnesstrax_gtk = crates.crates.fitnesstrax_gtk."0.1.0" deps;
  __all = [ (fitnesstrax_gtk {}) ];
  deps.aho_corasick."0.5.3" = {
    memchr = "0.1.11";
  };
  deps.aho_corasick."0.6.10" = {
    memchr = "2.2.1";
  };
  deps.aho_corasick."0.7.6" = {
    memchr = "2.2.1";
  };
  deps.atk."0.8.0" = {
    atk_sys = "0.9.1";
    bitflags = "1.2.1";
    glib = "0.9.0";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    libc = "0.2.66";
  };
  deps.atk_sys."0.9.1" = {
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    libc = "0.2.66";
    pkg_config = "0.3.17";
  };
  deps.autocfg."0.1.7" = {};
  deps.bitflags."1.2.1" = {};
  deps.byteorder."0.4.2" = {};
  deps.cairo_rs."0.8.0" = {
    bitflags = "1.2.1";
    cairo_sys_rs = "0.9.2";
    glib = "0.9.0";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    libc = "0.2.66";
  };
  deps.cairo_sys_rs."0.9.2" = {
    glib_sys = "0.9.1";
    libc = "0.2.66";
    pkg_config = "0.3.17";
  };
  deps.cc."1.0.48" = {};
  deps.cfg_if."0.1.10" = {};
  deps.chrono."0.4.10" = {
    num_integer = "0.1.41";
    num_traits = "0.2.10";
    serde = "1.0.104";
    time = "0.1.42";
  };
  deps.chrono_tz."0.4.1" = {
    chrono = "0.4.10";
    serde = "1.0.104";
    parse_zoneinfo = "0.1.1";
  };
  deps.dimensioned."0.7.0" = {
    generic_array = "0.11.1";
    num_traits = "0.2.10";
    serde = "1.0.104";
    typenum = "1.11.2";
  };
  deps.dtoa."0.4.4" = {};
  deps.emseries."0.4.0" = {
    chrono = "0.4.10";
    chrono_tz = "0.4.1";
    dimensioned = "0.7.0";
    serde = "1.0.104";
    serde_derive = "1.0.104";
    serde_json = "1.0.44";
    uuid = "0.6.5";
    yaml_rust = "0.4.3";
  };
  deps.fitnesstrax."0.1.0" = {
    chrono = "0.4.10";
    chrono_tz = "0.4.1";
    dimensioned = "0.7.0";
    emseries = "0.4.0";
    serde = "1.0.104";
    serde_derive = "1.0.104";
    serde_json = "1.0.44";
  };
  deps.fitnesstrax_gtk."0.1.0" = {
    chrono = "0.4.10";
    chrono_tz = "0.4.1";
    dimensioned = "0.7.0";
    emseries = "0.4.0";
    fitnesstrax = "0.1.0";
    gio = "0.8.0";
    glib = "0.8.2";
    gtk = "0.8.0";
    regex = "1.3.1";
    serde = "1.0.104";
    serde_yaml = "0.8.11";
    tzdata = "0.4.1";
  };
  deps.fuchsia_cprng."0.1.1" = {};
  deps.futures_channel."0.3.1" = {
    futures_core = "0.3.1";
  };
  deps.futures_core."0.3.1" = {};
  deps.futures_executor."0.3.1" = {
    futures_core = "0.3.1";
    futures_task = "0.3.1";
    futures_util = "0.3.1";
  };
  deps.futures_io."0.3.1" = {};
  deps.futures_macro."0.3.1" = {
    proc_macro_hack = "0.5.11";
    proc_macro2 = "1.0.6";
    quote = "1.0.2";
    syn = "1.0.11";
  };
  deps.futures_task."0.3.1" = {};
  deps.futures_util."0.3.1" = {
    futures_core = "0.3.1";
    futures_macro = "0.3.1";
    futures_task = "0.3.1";
    pin_utils = "0.1.0-alpha.4";
    proc_macro_hack = "0.5.11";
    proc_macro_nested = "0.1.3";
    slab = "0.4.2";
  };
  deps.gdk."0.12.0" = {
    bitflags = "1.2.1";
    cairo_rs = "0.8.0";
    cairo_sys_rs = "0.9.2";
    gdk_pixbuf = "0.8.0";
    gdk_sys = "0.9.1";
    gio = "0.8.0";
    gio_sys = "0.9.1";
    glib = "0.9.0";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    libc = "0.2.66";
    pango = "0.8.0";
  };
  deps.gdk_pixbuf."0.8.0" = {
    gdk_pixbuf_sys = "0.9.1";
    gio = "0.8.0";
    gio_sys = "0.9.1";
    glib = "0.9.0";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    libc = "0.2.66";
  };
  deps.gdk_pixbuf_sys."0.9.1" = {
    gio_sys = "0.9.1";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    libc = "0.2.66";
    pkg_config = "0.3.17";
  };
  deps.gdk_sys."0.9.1" = {
    cairo_sys_rs = "0.9.2";
    gdk_pixbuf_sys = "0.9.1";
    gio_sys = "0.9.1";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    libc = "0.2.66";
    pango_sys = "0.9.1";
    pkg_config = "0.3.17";
  };
  deps.generic_array."0.11.1" = {
    typenum = "1.11.2";
  };
  deps.gio."0.8.0" = {
    bitflags = "1.2.1";
    futures_channel = "0.3.1";
    futures_core = "0.3.1";
    futures_io = "0.3.1";
    futures_util = "0.3.1";
    gio_sys = "0.9.1";
    glib = "0.9.0";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    lazy_static = "1.4.0";
    libc = "0.2.66";
  };
  deps.gio_sys."0.9.1" = {
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    libc = "0.2.66";
    pkg_config = "0.3.17";
  };
  deps.glib."0.8.2" = {
    bitflags = "1.2.1";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    lazy_static = "1.4.0";
    libc = "0.2.66";
  };
  deps.glib."0.9.0" = {
    bitflags = "1.2.1";
    futures_channel = "0.3.1";
    futures_core = "0.3.1";
    futures_executor = "0.3.1";
    futures_task = "0.3.1";
    futures_util = "0.3.1";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    lazy_static = "1.4.0";
    libc = "0.2.66";
  };
  deps.glib_sys."0.9.1" = {
    libc = "0.2.66";
    pkg_config = "0.3.17";
  };
  deps.gobject_sys."0.9.1" = {
    glib_sys = "0.9.1";
    libc = "0.2.66";
    pkg_config = "0.3.17";
  };
  deps.gtk."0.8.0" = {
    atk = "0.8.0";
    bitflags = "1.2.1";
    cairo_rs = "0.8.0";
    cairo_sys_rs = "0.9.2";
    gdk = "0.12.0";
    gdk_pixbuf = "0.8.0";
    gdk_pixbuf_sys = "0.9.1";
    gdk_sys = "0.9.1";
    gio = "0.8.0";
    gio_sys = "0.9.1";
    glib = "0.9.0";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    gtk_sys = "0.9.2";
    lazy_static = "1.4.0";
    libc = "0.2.66";
    pango = "0.8.0";
    pango_sys = "0.9.1";
  };
  deps.gtk_sys."0.9.2" = {
    atk_sys = "0.9.1";
    cairo_sys_rs = "0.9.2";
    gdk_pixbuf_sys = "0.9.1";
    gdk_sys = "0.9.1";
    gio_sys = "0.9.1";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    libc = "0.2.66";
    pango_sys = "0.9.1";
    pkg_config = "0.3.17";
  };
  deps.itoa."0.4.4" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.lazy_static."1.4.0" = {};
  deps.libc."0.2.66" = {};
  deps.linked_hash_map."0.5.2" = {};
  deps.memchr."0.1.11" = {
    libc = "0.2.66";
  };
  deps.memchr."2.2.1" = {};
  deps.num_integer."0.1.41" = {
    num_traits = "0.2.10";
    autocfg = "0.1.7";
  };
  deps.num_traits."0.2.10" = {
    autocfg = "0.1.7";
  };
  deps.pango."0.8.0" = {
    bitflags = "1.2.1";
    glib = "0.9.0";
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    lazy_static = "1.4.0";
    libc = "0.2.66";
    pango_sys = "0.9.1";
  };
  deps.pango_sys."0.9.1" = {
    glib_sys = "0.9.1";
    gobject_sys = "0.9.1";
    libc = "0.2.66";
    pkg_config = "0.3.17";
  };
  deps.parse_zoneinfo."0.1.1" = {
    regex = "0.2.11";
  };
  deps.pin_utils."0.1.0-alpha.4" = {};
  deps.pkg_config."0.3.17" = {};
  deps.proc_macro_hack."0.5.11" = {
    proc_macro2 = "1.0.6";
    quote = "1.0.2";
    syn = "1.0.11";
  };
  deps.proc_macro_nested."0.1.3" = {};
  deps.proc_macro2."1.0.6" = {
    unicode_xid = "0.2.0";
  };
  deps.quote."1.0.2" = {
    proc_macro2 = "1.0.6";
  };
  deps.rand."0.4.6" = {
    rand_core = "0.3.1";
    rdrand = "0.4.0";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.66";
    winapi = "0.3.8";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.2";
  };
  deps.rand_core."0.4.2" = {};
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.redox_syscall."0.1.56" = {};
  deps.regex."0.1.80" = {
    aho_corasick = "0.5.3";
    memchr = "0.1.11";
    regex_syntax = "0.3.9";
    thread_local = "0.2.7";
    utf8_ranges = "0.1.3";
  };
  deps.regex."0.2.11" = {
    aho_corasick = "0.6.10";
    memchr = "2.2.1";
    regex_syntax = "0.5.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.4";
  };
  deps.regex."1.3.1" = {
    aho_corasick = "0.7.6";
    memchr = "2.2.1";
    regex_syntax = "0.6.12";
    thread_local = "0.3.6";
  };
  deps.regex_syntax."0.3.9" = {};
  deps.regex_syntax."0.5.6" = {
    ucd_util = "0.1.5";
  };
  deps.regex_syntax."0.6.12" = {};
  deps.ryu."1.0.2" = {};
  deps.serde."1.0.104" = {
    serde_derive = "1.0.104";
  };
  deps.serde_derive."1.0.104" = {
    proc_macro2 = "1.0.6";
    quote = "1.0.2";
    syn = "1.0.11";
  };
  deps.serde_json."1.0.44" = {
    itoa = "0.4.4";
    ryu = "1.0.2";
    serde = "1.0.104";
  };
  deps.serde_yaml."0.8.11" = {
    dtoa = "0.4.4";
    linked_hash_map = "0.5.2";
    serde = "1.0.104";
    yaml_rust = "0.4.3";
  };
  deps.slab."0.4.2" = {};
  deps.syn."1.0.11" = {
    proc_macro2 = "1.0.6";
    quote = "1.0.2";
    unicode_xid = "0.2.0";
  };
  deps.thread_id."2.0.0" = {
    kernel32_sys = "0.2.2";
    libc = "0.2.66";
  };
  deps.thread_local."0.2.7" = {
    thread_id = "2.0.0";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.4.0";
  };
  deps.time."0.1.42" = {
    libc = "0.2.66";
    redox_syscall = "0.1.56";
    winapi = "0.3.8";
  };
  deps.typenum."1.11.2" = {};
  deps.tzdata."0.4.1" = {
    byteorder = "0.4.2";
    regex = "0.1.80";
    time = "0.1.42";
  };
  deps.ucd_util."0.1.5" = {};
  deps.unicode_xid."0.2.0" = {};
  deps.utf8_ranges."0.1.3" = {};
  deps.utf8_ranges."1.0.4" = {};
  deps.uuid."0.6.5" = {
    cfg_if = "0.1.10";
    rand = "0.4.6";
    serde = "1.0.104";
  };
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.8" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.yaml_rust."0.4.3" = {
    linked_hash_map = "0.5.2";
  };
}
