[package]
name = "fitnesstrax-gtk"
authors = ["savanni"]
edition = "2018"
version = "0.0.5-pre"

[dependencies]
chrono-tz = { version = "0.4", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
dimensioned = "0.7.0"
emseries = "0.4.0"
fitnesstrax = { path = "../fitnesstrax-lib" }
fluent = "0.9.1"
gio = { version = "", features = ["v2_44"] }
glib = "0.9.0"
gtk = { version = "0.8.0", features = ["v3_16"] }
regex = "1.3.1"
serde = { version = "1.0.102", features = ["derive"] }
serde_yaml = "*"
tzdata = "0.4.1"
unic-langid = "0.7.1"

[[bin]]
name = "fitnesstrax-gtk"
path = "src/main.rs"
